name: weather
description: Wheater and Paint.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.1.15
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
